config/routes.rb
Rails.application.routes.draw do
  get 'notifications/index'

  get 'top/index'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  
  devise_for :users, controllers: {
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks"
  }
  
  root 'top#index'
  
  resources :topics do
    resources :comments
  end
  
  resources :comments, only: [:edit, :update, :destroy]
  
  resources :users, only: [:index, :show, :edit, :update]
  
  resources :relationships, only: [:create, :destroy]
  
  resources :conversations do
    resources :messages
  end

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/models/topic.rb
class Topic < ActiveRecord::Base
  belongs_to :user
  has_many :comments, dependent: :destroy
  validates :content, presence: true
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_topic, only: [:show, :edit, :update, :destroy]
  
  def index
    @topics = Topic.all.order(created_at: :desc)
    @topic = Topic.new
    @users = User.all
    @followed = current_user.followed_users
    @followers = current_user.followers
  end

  def new
    @topic = Topic.new
  end

  def create
    @topic = Topic.new(topics_params)
    @topic.user_id = current_user.id
    if @topic.save
      redirect_to topics_path, notice: "投稿しました！"
      NoticeMailer.sendmail_topic(@topic).deliver
    else
      
      render action: 'new'
    end
  end
  
  def show
    @comment = @topic.comments.build
    @comments = @topic.comments
    Notification.find(params[:notification_id]).update(read: true) if params[:notification_id]
  end  
  
  def edit
  end

  def update
    @topic.update(topics_params)
    redirect_to topics_path
  end
  
  def destroy
    @topic.destroy
    redirect_to topics_path, notice: "削除しました！"
  end
  private
    def topics_params
      params.require(:topic).permit(:content)
    end
    
    def set_topic
      @topic = Topic.find(params[:id])
    end
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/_form.html.erb
<%= form_for(@topic) do |f| %>
  <%= f.error_messages! %>

  <br>
  <%= f.text_field :content, placeholder: "今なにしてる？", class: 'form-control' %>
  <br>
  <%= f.submit '投稿', class: 'btn btn-primary btn-block' %>
<% end %>

<%= link_to "投稿一覧画面にもどる", topics_path %>

app/views/topics/edit.html.erb
<div class="container">
  <div class="wrapper col-md-8 col-md-offset-2 col-sm-10">
    <%= render 'form' %>
  </div>
</div>

app/views/topics/index.html.erb
<div class="container">
  <div class="wrapper col-md-8 col-md-offset-2 col-sm-10">
    <%= form_for(@topic) do |f| %>
      <%= f.text_field :content, placeholder: "今なにしてる？", class: 'form-control' %>
      <%= f.submit '投稿', class: 'btn btn-primary btn-block' %>
    <% end %>
    <br><br>
      <% @topics.each do |topic| %>
        <% @followed.each do |followed| %>
          <% @followers.each do |followers| %>
            <% if topic.user.id == followed.id && topic.user.id == followers.id %>
            <div class="row">
              <div class="prof-img">
                <%= profile_img(topic.user) if profile_img(topic.user) %>
              </div>
              <p><%= topic.content %></p>
              <%= link_to topic_path(topic) do %>
                <strong>コメントする</strong>
                <br>
              <% end %>
              <%= link_to "編集する", edit_topic_path(topic.id) %>
              <%= link_to '削除する', topic_path(topic), method: :delete, data: { confirm: '本当に削除していいですか？' } %>
            </div>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
      <% @topics.each do |topic| %>
        <% if topic.user.id == current_user.id %>
            <div class="row">
              <div class="prof-img">
                <%= profile_img(topic.user) if profile_img(topic.user) %>
              </div>
              <p><%= topic.content %></p>
              <%= link_to topic_path(topic) do %>
                <strong>コメントする</strong>
                <br>
              <% end %>
              <%= link_to "編集する", edit_topic_path(topic.id) %>
              <%= link_to '削除する', topic_path(topic), method: :delete, data: { confirm: '本当に削除していいですか？' } %>
            </div>
        <% end %>
      <% end %>      
  </div>
</div>
<div id="page-top-btn" class="page-top-btn">
    <p><a class="move-page-top" id="move-page-top">▲</a></p>
</div>

app/views/topics/new.html.erb
<div class="container">
  <div class="wrapper col-md-8 col-md-offset-2 col-sm-10">
    <%= render 'form' %>
  </div>
</div>

app/views/topics/show.html.erb
<p id="notice"><%= notice %></p>
<div class="child row">
  <div class="wrapper col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
    <div class="blog-text">
      <p class="left"><strong>内容</strong></p>
      <p class="left"><%= @topic.content %></p>
      <p class="right">
        <strong>作成時間:</strong>
        <%= @topic.created_at.strftime("%y/%m/%d %p %l:%M") %>
      </p>
    </div>
    <p>コメント一覧</p>
    <div id="comments_area">
      <%= render partial: 'comments/index', locals: { comments: @comments, topic: @topic } %>
    </div>
    <%= render partial: 'comments/form', locals: { comment: @comment, topic: @topic } %>
    <% if current_user.id == @topic.user_id %>
      <%= link_to '編集', edit_topic_path(@topic) %> |
    <% end %>
    <%= link_to '戻る', topics_path %>
  </div>
</div>