config/routes.rb
Rails.application.routes.draw do
  get 'notifications/index'

  get 'top/index'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  
  devise_for :users, controllers: {
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks"
  }
  
  root 'top#index'
  
  resources :topics do
    resources :comments
  end
  
  resources :comments, only: [:edit, :update, :destroy]
  
  resources :users, only: [:index, :show, :edit, :update]
  
  resources :relationships, only: [:create, :destroy]
  
  resources :conversations do
    resources :messages
  end

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  mount_uploader :avatar, AvatarUploader
  
  has_many :topics, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :relationships, foreign_key: "follower_id", dependent: :destroy
  has_many :reverse_relationships, foreign_key: "followed_id", class_name: "Relationship", dependent: :destroy
  has_many :followed_users, through: :relationships, source: :followed
  has_many :followers, through: :reverse_relationships, source: :follower
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable, :omniauthable

  def self.find_for_twitter_oauth(auth, signed_in_resource = nil)
    user = User.where(provider: auth.provider, uid: auth.uid).first

    unless user
      user = User.new(
          name:     auth.info.nickname,
          image_url: auth.info.image,
          provider: auth.provider,
          uid:      auth.uid,
          email:    auth.info.email ||= "#{auth.uid}-#{auth.provider}@example.com",
          password: Devise.friendly_token[0, 20]
      )
      user.skip_confirmation!
      user.save
    end
    user
  end
  
  def self.create_unique_string
    SecureRandom.uuid
  end
  
  def update_with_password(params, *options)
    if provider.blank?
      super
    else
      params.delete :current_password
      update_without_password(params, *options)
    end
  end
  
  def follow!(other_user)
    relationships.create!(followed_id: other_user.id)
  end

  def following?(other_user)
    relationships.find_by(followed_id: other_user.id)
  end
  
  def unfollow!(other_user)
    relationships.find_by(followed_id: other_user.id).destroy
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def twitter
    @user = User.find_for_twitter_oauth(request.env["omniauth.auth"], current_user)

    if @user.persisted?
      set_flash_message(:notice, :success, kind: "Twitter") if is_navigational_format?
      sign_in_and_redirect @user, event: :authentication
    else
      session["devise.twitter_data"] = request.env["omniauth.auth"].except("extra")
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  def build_resource(hash=nil)
    hash[:uid] = User.create_unique_string
    super
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
    @followed = current_user.followed_users
    @followers = current_user.followers
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/users/omniauth_callbacks_helper.rb
module Users::OmniauthCallbacksHelper
end

app/helpers/users/registrations_helper.rb
module Users::RegistrationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_follow_form.html.erb
<div id="follow_form_<%= user.id %>">
  <% unless current_user.following?(user) %>
    <%= form_for(current_user.relationships.build(followed_id: user.id), remote: true) do |f| %>
      <%= f.hidden_field :followed_id %>
      <%= f.submit "フォロー", class: "btn btn-large btn-primary" %>
    <% end %>
  <% else %>
    <%= form_for(current_user.relationships.find_by(followed_id: user.id), html: { method: :delete }, remote: true) do |f| %>
      <%= f.submit "つながりを解除", class: "btn btn-large" %>
    <% end %>
  <% end %>
</div>

app/views/users/_followed_users.html.erb
<div class="container">
  <h2>フォロー</h2>
  <% @user.followed_users.each do |followed| %>
      <div class="container-child col-md-2 col-sm-4 col-xs-6 ">
        <div class="user-padding">
          <%= profile_img(followed) %>
          <div class="line-break">
            <%= followed.email %>
          </div>
          <% if @user.id == current_user.id %>
          <%= render 'follow_form', user: followed %>
          <% end %>
        </div>
      </div>
  <% end %>
</div>

app/views/users/_followers.html.erb
<div class="container">
  <h2>フォロワー</h2>
  <% @user.followers.each do |followers| %>
      <div class="container-child col-md-2 col-sm-4 col-xs-6 ">
        <div class="user-padding">
          <%= profile_img(followers) %>
          <div class="line-break">
            <%= followers.email %>
          </div>
        </div>
      </div>
  <% end %>
</div>

app/views/users/index.html.erb
<div class="container">
  <h2>ユーザー</h2>
  <% @users.each do |user| %>
      <div class="container-child col-md-2 col-sm-4 col-xs-6 ">
        <div class="user-padding">
          <%= profile_img(user) %>
          <div class="line-break">
            <%= user.email %>
          </div>
          <%= link_to "詳細", user_path(user) %>
          <% if user.id != current_user.id %>
            <li>
              <div class="item">
                <%= link_to user.name, user %>
                <br>
                <% @followed.each do |followed| %>
                  <% @followers.each do |followers| %>
                    <% if user.id == followed.id && user.id == followers.id %>
                      <%= link_to 'メッセージ', conversations_path(sender_id: current_user.id, recipient_id: user.id), method: 'post'%>
                    <% end %>
                  <% end %>
                <% end %>
              </div>
              <%= render partial: 'follow_form', locals: { user: user } if signed_in?   %>
            </li>
          <% end %>
        </div>
      </div>
  <% end %>
</div>

app/views/users/show.html.erb
<%= render 'followed_users' %>
<%= render 'followers' %>